version: "3"
services:
        web:
                container_name: web
                build: .
                ports:
                        - 80:5000
                        - 443:5001
                volumes:
                        - .:/project
                command:
                        sh -c "npm run build && nodemon --legacy-watch server/app"
